version: "3.6"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
  backend:
    build:
      context: ./CursusCase.Backend
      dockerfile: Dockerfile
    ports:
      - 7236:80
    image: kcbdregistry.azurecr.io/anthony/cursus-case-backend:latest
    environment:
      ConnectionStrings__TodoContext: 'Server=sql-server-db; Database=Todo; User=sa; Password=${SA_PASSWORD}; TrustServerCertificate=true;'
  frontend:
    build:
      context: ./CursusCase.FrontEnd
      dockerfile: Dockerfile
    ports:
      - 5000:80
    image: kcbdregistry.azurecr.io/anthony/cursus-case-frontend:latest
